.phony all:
all: p1 test5 test100 inf infinv

p1: p1.c
	gcc p1.c -lreadline -lhistory -ltermcap -o p1

test5: test5.c
	gcc test5.c -o test5

test100: test100.c
	gcc test100.c -o test100

inf: inf.c
	gcc inf.c -o inf

infinv: infinv.c
	gcc infinv.c -o infinv